# Use an official Python runtime as a base image
FROM python:3.12-slim

# Set the working directory to /app
WORKDIR /app

# necessary for building some of the Python libraries - chromadb, etc.
RUN apt-get update --fix-missing && apt-get install -y --fix-missing build-essential

# Copy the requirements file into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

CMD tail -f /dev/null